server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/himani_roaster
spring.datasource.username=postgres
spring.datasource.password=Omsairam@12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=iamchoudharyshivamdeshwalsecretuk08aj2552;
jwt.expiration=360000

